coverage:
  range: 80..95
  round: down
  precision: 1
  status:
    project:
      default:
        # basic
        target: 95
        base: auto
    patch:
      default:
        target: 90
        base: auto
